FROM debezium/connect-base:2.1

USER root

RUN curl -O https://api.hub.confluent.io/api/plugins/confluentinc/kafka-connect-datagen/versions/0.6.0/confluentinc-kafka-connect-datagen-0.6.0.zip
RUN unzip -d /usr/share/java confluentinc-kafka-connect-datagen-0.6.0.zip

RUN curl -O https://api.hub.confluent.io/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.2.2/confluentinc-kafka-connect-avro-converter-7.2.2.zip
RUN unzip -d /usr/share/java confluentinc-kafka-connect-avro-converter-7.2.2.zip

RUN curl -o /usr/share/java/confluentinc-kafka-connect-avro-converter-7.2.2/lib/guava-11.0.2.jar -O https://repo1.maven.org/maven2/com/google/guava/guava/11.0.2/guava-11.0.2.jar
